### PR TITLE
Store and compare overrides with `pwd -P`. Issue #40

### PR DESCRIPTION
**Pull request by brson**

### CODE REVIEW

**Comment by brson** [comment]
cc @gsingh93

**Comment by brson** [comment]
Oh, as written this patch is no good since it is a hard error if _any_ overrides can't be converted to physical path, but this is basically how I think this should be solved.

**Comment by brson** [comment]
Updated so the script won't fail if any override doesn't exist.

**Comment by gsingh93** [comment]
Looking at the code, it looks like it should work. If I run `echo $(cd /somedir && pwd -P)`, it prints out the actual directory name. However, when I run this branch, it doesn't work. If I add an echo statement after `local _ovrdir="$(cd "$_ovrdir" && pwd -P)"`, it prints the symlink directory name, not the real name. I'm not sure what's going on.

**Pull request merged**
