### PR TITLE
Better error handling for `which`

### PR DESCRIPTION
**Pull request by tamird**
@brson also fixed indentation in `src/multirust`. Sorry for the big diff, but it was a mess :(

### CODE REVIEW

**Comment by brson** [comment]
Huh, I guess my emacs is not configured right. Do you mind switching to spaces instead of tabs, as that's the Rust convention?

**Comment by tamird** [comment]
two spaces?

**Comment by brson** [comment]
Four, please.

**Comment by tamird** [comment]
Done.

**Pull request merged**
