### PR TITLE
Consider `.multirust` as part of multirust's home

### PR DESCRIPTION
**Pull request by flaper87**
There's no need to have a separate home besides `.multirust`. It can be
confusing to have set MULTIRUST_HOME and find out that multirust creates
a hidden dir in that home as well.

### CODE REVIEW

**Comment by flaper87** [comment]
the PR also changes the use of tabs with spaces and adds a travis config file

**Comment by brson** [comment]
This fails on OS X with

```
rust-mac6:multirust administrator$ ./test.sh
test: building mock channel 1.0.0-nightly hash-nightly-1 nightly nightly 2015-01-01
test: gpg not found. not testing signature verification
test: building mock channel 1.0.0-beta hash-beta-1 beta beta 2015-01-01
test: gpg not found. not testing signature verification
test: building mock channel 1.0.0 hash-stable-1 1.0.0 stable 2015-01-01
test: gpg not found. not testing signature verification
test: building mock channel 1.1.0-nightly hash-nightly-2 nightly nightly 2015-01-02
test: gpg not found. not testing signature verification
test: building mock channel 1.1.0-beta hash-beta-2 beta beta 2015-01-02
test: gpg not found. not testing signature verification
test: building mock channel 1.1.0 hash-stable-2 1.1.0 stable 2015-01-02
test: gpg not found. not testing signature verification
test: building multirust
test: uninitialized
test: default toolchain
test: expected bins exist
test: install toolchain from channel
test: install toolchain from archive
test: install toolchain from version
test: default existing toolchain
test: update channel
$ rustc --version
rustc 1.1.0-nightly (hash-nightly-2 2014-12-24 20:47:12 +0000)

missing expected output 'hash-nightly-1'


TEST FAILED!
```

**Comment by brson** [comment]
I can investigate later when I'm not tethered.

**Comment by brson** [comment]
Also my question from IRC:

```
14:32 <@brson> flaper87: do you know of precedent for other _HOME directories? cargo's CARGO_HOME is a standin for $HOME, iow cargo also creates a separate .cargo under CARGO_HOME
14:32 <@brson> both of these were set up by me though
14:32 <@brson> and there may be other precedent
```

**Comment by brson** [comment]
Please put the MULTIRUST_HOME patch in a separate PR so we can wait to see how @alexcrichton responds to the equivalent cargo patch.

**Comment by flaper87** [comment]
@brson  just split this PR.

Also, my replies from IRC:

``` irc
23:34:23 flaper87 brson: I'm mostly basing that on how virtualenvwrapper does things: http://virtualenvwrapper.readthedocs.org/en/latest/install.html                   
23:34:55 flaper87 brson: the WORKON_HOME, which is our MULTIRUST_HOME, points to the place where it creates all the things                                              
23:35:14 flaper87 brson: what would we put in MULTIRUST_HOME other than `.multirust` ? 
23:35:21 @brson flaper87: nothing                                                                                                                                        
23:35:34 @brson i was just thinking that it was a substitute for $HOME                                                                                                   
23:35:46 @brson like a custom override for HOME                                                                                                                                                                                                          
23:36:30 flaper87 mmh, then I'd probably just go with using MULTIRUST_HOME as a replacement for `.multirust` (like in that PR)                                           
23:37:32 @brson if we do that then we should probably also change cargo                                                                                                                                                                                                        
23:37:59 @brson flaper87: can you put that patch in a separate pr so we can deal with cargo at the same time?                                                            
23:38:09 flaper87 brson: I'd vote for that, fwiw. I can do it myself too :D                                                                                              
23:38:14 flaper87 brson: yup                                                                                                                                             
23:38:17 flaper87 let me split it                                                                                                                                        
23:38:37 @brson larsberg: ^ flaper87 is going to submit a patch to cargo that slightly changes what CARGO_HOME means                                                     
23:38:53 @brson instead of being the directory above .cargo it would be the .cargo directory                                                                             
23:39:08 @brson atm this should only affect multirust and servo                                                                                                          

```

**Comment by brson** [comment]
cc https://github.com/rust-lang/cargo/pull/1148

**Comment by flaper87** [comment]
@brson I believe this commit was merged, can we close this PR ?

**Comment by brson** [comment]
It's not merged yet. `test.sh` needs to be updated to understand the new definition of `MULTIRUST_HOME`:

```
brian@brianX1:~/dev/multirust⟫ ./test.sh
test: building mock channel 1.0.0-nightly hash-nightly-1 nightly nightly 2015-01-01
test: building mock channel 1.0.0-beta hash-beta-1 1.0.0-beta beta 2015-01-01
test: building mock channel 1.0.0 hash-stable-1 1.0.0 stable 2015-01-01
test: building mock channel 1.1.0-nightly hash-nightly-2 nightly nightly 2015-01-02
test: building mock channel 1.1.0-beta hash-beta-2 1.1.0-beta beta 2015-01-02
test: building mock channel 1.1.0 hash-stable-2 1.1.0 stable 2015-01-02
test: building multirust
test: uninitialized
test: default toolchain
test: expected bins exist
test: install toolchain from channel
test: install toolchain from archive
test: install toolchain from version
test: default existing toolchain
test: update channel
$ rustc --version
rustc 1.1.0-nightly (hash-nightly-2 2014-12-24 20:47:12 +0000)

missing expected output 'hash-nightly-1'


TEST FAILED!
```

**Comment by flaper87** [comment]
@brson doh! my local copy log confused me. Fixing that.

**Pull request merged**
