### PR TITLE
Add support for `which` command as per request #36.

### PR DESCRIPTION
**Pull request by shaleh**
As the subject says, add support for `multirust which cmd` as per #36.

### CODE REVIEW

**Comment by brson** [comment]
Thanks! Looks good except for the notes.

**Comment by brson** [comment]
Thanks again.

**Comment by tamird** [comment]
@brson perhaps the error handling is needed after all; running `multirust which` without an argument results in a puzzling error message `/usr/local/bin/multirust: line 1288: $1: unbound variable`

**Comment by brson** [comment]
@tamird oh, hm, thanks for verifying. I expected the input to be sanitized elsewhere, probably during argument parsing, and thought that check was defensive. Do you mind putting that check in `handle_command_line_args`? There are some existing argument checks there to crib off of.

**Pull request merged**
