### PR TITLE
V2 manifests

### PR DESCRIPTION
**Pull request by brson**
This teaches multirust to read [V2 manifests](https://github.com/rust-lang/rust-buildbot/pull/44). It adds the `list-available-targets <toolchain>` and `add-target <toolchain>` commands.

This has only been unit tested on Linux, Windows and Mac, not tested live, so don't merge yet.

I'll be happy to squash if this history is too ugly.

r? @alexcrichton cc @edunham

### CODE REVIEW

**Comment by alexcrichton** [comment]
lgtm, r=me when this is ready

**Comment by SimonSapin** [comment]
I didn’t manage to make this work. Am I missing some install step?

```
$ multirust list-available-targets nightly
rustup: no channel manifest at '/home/simon/tmp/multirust/toolchains/nightly/lib/rustlib/channel-manifest.toml'
$ multirust add-target nightly arm-linux-androideabi
rustup: no channel manifest at '/home/simon/tmp/multirust/toolchains/nightly/lib/rustlib/channel-manifest.toml'
```

**Comment by brson** [comment]
@SimonSapin The infrastructure necessary to make this work [hasn't been deployed yet](https://github.com/rust-lang/rust-buildbot/pull/44).

**Comment by lberezy** [comment]
What's the status of this? [Apparently](https://github.com/japaric/rust-cross) simple cross-compliation is waiting on this to land.

There seems to be work happening on the `new` branch [here](https://github.com/Diggsey/multirust-rs/tree/new).

**Comment by brson** [comment]
@lberezy Still waiting on support in [rust-buildbot](https://github.com/rust-lang/rust-buildbot/pull/44) to generate the correct metadata. It is actively being worked on this week.

**Pull request merged**
