### PR TITLE
adding autocomplete for linux

### PR DESCRIPTION
**Pull request by chyzwar**
I tested this on Ubuntu, You might need to test this on other distro.

### CODE REVIEW

**Comment by brson** [comment]
Thanks!

**Comment by chyzwar** [comment]
I moved this to build/image/bash_completion, but you will need add this to install.sh. 

Also can you check if autocompletion for remove-overwrite is ok with you. To test autocomplete you only need to source the thing.

**Comment by brson** [comment]
What about the remove-override autocomplete concerns you? It looks like the others to me.

**Comment by nerdrew** [comment]
Any movement on this? I added zsh completion in my fork of the multirust homebrew formula: https://github.com/nerdrew/homebrew-tap/blob/master/multirust.rb

Any decision on the best way to install the completions?

**Comment by brson** [comment]
@nerdrew It looks to me like cargo installs its zsh completions to `/usr/local/share/site-functions`. Will zsh pick up the completions there?

What I suggest we do is:
- Adjust this patch's build.sh to copy the bash completions to `build/image/etc/bash_completion.d/multirust`. That way it will be default it will be installed to `/usr/local/etc/bash_completion.d` (which will _not_ be picked up by bash by default).
- (If the user happens to install with `--prefix=/usr` then it will be picked up by bash)
- Add code to this repo's install.sh that detects if the users shell is bash and if installing to `/usr/local` and suggests adding the appropriate code to their `~/.bashrc` file to source the multirust completions.

@nerdrew Similarly, add zsh completions to `build/image/share/site-functions/` so they will be installed, and if that location isn't sufficient to pick up by default add a helpful message during installation.

Getting the bash completions in the real correct place to just work will require modifications to rust-installer that I'm not sure of yet.

**Comment by nerdrew** [comment]
Does cargo install the zsh completions in `/usr/local/share/site-functions` or in `/usr/local/share/zsh/site-functions`?

**Comment by brson** [comment]
@nerdrew, oh the latter. good catch.

**Comment by chyzwar** [comment]
I think this is no longer needed.

**Pull request closed without merging**
