### PR TITLE
Allow for overrides to link/copy local toolchains

### PR DESCRIPTION
**Pull request by flaper87**

### CODE REVIEW

**Comment by brson** [comment]
If we did this I would probably want to couple it to a toolchain installation command instead of the override command, like the current `update` accepts `--custom` to install a toolchain, which can then be used with `default` on `override`. Probably it would be part of the `update` command, though the word 'update' starts to feel a bit incorrect.

I'd rather not override the `--custom` flag to do both this and the existing installation from a custom tarball installer.

Can you describe again your use case? Is it just for installing the snapshots as a toolchain, and if so why is that more convenient than letting the build system manage the snaps?

**Comment by flaper87** [comment]
It's not just for the snapshot, although this feature may work for that as well.

One use case is being able to use the builds I have in my working copy. Say I'm working on a feature and I want to use that toolchain for building a project. Right now, I'd have to export the library path and use a full path to my local rustc binary.

```
LD_LIBRARY_PATH=x86_64-unknown-linux-gnu/stage1/lib:$LD_LIBRARY_PATH x*/*1/bin/rustc
```

While this is doable, it's a bit annoying. Instead, I could simply create a new `toolchain` using multirust and link to that path. When I'm done, I can delete it and move on.

Something I like about python's virtualenv - virtualenv allows you to create "virtual" python environment, which are isolated from the system one - is that it lets you choose the local binary you want to create the virtualenv from.

```
virtualenv --python=python2.7 --no-site-packages .venv
```

multirust does this but it needs to download the toolchain if it doesn't exist even if you have it already somewhere in your system.

I agree `--custom` is not the right flag here and that it should go in the `update` command. We could actually proxy `update` flags through `override` by making `update` us `install_toolchain_if_not_installed`. What about using `--use-local` instead of `--custom` for this case and changing the existing `--custom` with `--use-package`?

**Comment by brson** [comment]
Thanks for the explanation @FlaPer87. @erickt has also asked for a similar feature. I do think I want to tweak the design here a bit. I'll put more thought to it and get back to you soon.

**Comment by brson** [comment]
@FlaPer87 I basically agree with your design as stated, assuming these go into the `update` command. My one qualm is the symlink case which I think will be common, and here requires an extra argument. What about something like `--copy-local`, `--link-local`, `--use-package`?

I'm still not sure yet whether I want to add these to `default` and `override` but perhaps that's inevitable for convenience.

**Comment by brson** [comment]
Sorry for taking so long to get back to you about this. It's taken several people asking for it to convince me it's necessary.

**Comment by flaper87** [comment]
@brson np at all.

So, I'd probably go with `--copy-local` and `--link-local` just to make sure it's understandable from the command itself what's going to happen.

As far as proxing this through `default` and `override`, I'd probably do it. It's convenient and it's also consistent with the way default, override and update work right now. I'll update the patch.

**Comment by brson** [comment]
Thanks, and sorry for all the nitpicks, but I'm still very protective of multirust.

**Comment by flaper87** [comment]
@brson np at all. Will address them asap. Thanks for the review :+1:

**Pull request merged**
